name: fa_dart_logger
description: Official FA Dart logger package.
version: 1.0.0
author: Ayush P Gupta <ayushpguptaapg@gmail.com>
homepage: https://github.com/FieldAssist/fa_dart_logger.git

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  ansicolor: ^1.1.1
  logger: ^0.9.4

dev_dependencies:
  pedantic: ^1.11.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec