name: fa_dart_logger
description: Official FA Dart logger package.
version: 1.0.0
author: Ayush P Gupta <ayushpguptaapg@gmail.com>
homepage: https://github.com/FieldAssist/fa_dart_logger.git

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  ansicolor: ^2.0.2
  logger: ^2.2.0

dev_dependencies:
  lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec